#ifndef PINDEFINATION
#define PINDEFINATION

#define BM8563_I2C_SDA 21
#define BM8563_I2C_SCL 22

#define PIN_OUTPUT_HALL_SENSOR 32

#define PIN_INPUT_HALL_SENSOR_DOOR 35
#define PIN_INPUT_HALL_SENSOR_FEED 34

#define PIN_OUTPUT_DOOR_CLOSE 33
#define PIN_OUTPUT_DOOR_OPEN 25

#define PIN_OUTPUT_FEED_OPEN 26

#define PIN_INPUT_COVER_STATE 14
#define PIN_OUTPUT_COVER_IR 27
#define PIN_INPUT_FOOD_LEVEL 15

// LED
#define PIN_OUTPUT_LED_WIFI_DEVICE_READY 4 //r29
#define PIN_OUTPUT_LED_DISPENSING 5 //r28
#define PIN_OUTPUT_LED_COVER_OPEN 19 //r50
#define PIN_OUTPUT_LED_LOW_LEVEL 18 //r27

#define PIN_INPUT_MANUAL_FEEDER  23

#endif /* PINDEFINATION */
